jQuery(document).ready(function() {
	jQuery('#ui-id-1').click(function(){
		jQuery('#option_general').show();
		jQuery('#option_logo_header').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_home').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_color_header1').hide();
		jQuery('#option_slug_settings').hide();
		jQuery('#home_layout_setting').hide();	
		jQuery('#option_banner_header').hide();
		});
	
	jQuery('#ui-id-2').click(function(){
		jQuery('#option_typography').show();
		jQuery('#option_general').hide();
		jQuery('#option_logo_header').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_home').hide();
		jQuery('#option_color_header1').hide();
		jQuery('#option_slug_settings').hide();
		jQuery('#home_layout_setting').hide();	
		jQuery('#option_banner_header').hide();
	});
	
	jQuery('#ui-id-3').click(function(){
		jQuery('#option_logo_header').show();
		jQuery('#option_general').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_home').hide();
		jQuery('#option_color_header1').hide();
		jQuery('#option_slug_settings').hide();
		jQuery('#home_layout_setting').hide();	
		jQuery('#option_banner_header').hide();
	});
	
	jQuery('#ui-id-4').click(function(){
		jQuery('#option_footer').show();
		jQuery('#option_general').hide();
		jQuery('#option_logo_header').hide();
		jQuery('#option_home').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_color_header1').hide();
		jQuery('#option_slug_settings').hide();	
		jQuery('#home_layout_setting').hide();	
		jQuery('#option_banner_header').hide();
	});
	
	jQuery('#ui-id-5').click(function(){
		jQuery('#option_home').show();
		jQuery('#option_general').hide();
		jQuery('#option_logo_header').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_color_header1').hide();
		jQuery('#option_slug_settings').hide();	
		jQuery('#home_layout_setting').hide();	
		jQuery('#option_banner_header').hide();
	});
	jQuery('#ui-id-6').click(function(){
		jQuery('#option_color_header1').show();
		jQuery('#option_home').hide();
		jQuery('#option_general').hide();
		jQuery('#option_logo_header').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_slug_settings').hide();	
		jQuery('#option_banner_header').hide();
		jQuery('#home_layout_setting').hide();	
	});
	jQuery('#ui-id-7').click(function(){
		jQuery('#option_color_header1').hide();
		jQuery('#option_home').hide();
		jQuery('#option_general').hide();
		jQuery('#option_logo_header').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_slug_settings').show();
		jQuery('#option_banner_header').hide();
		jQuery('#home_layout_setting').hide();	
	});
	jQuery('#ui-id-8').click(function(){
		jQuery('#option_color_header1').hide();
		jQuery('#option_home').hide();
		jQuery('#option_general').hide();
		jQuery('#option_logo_header').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_slug_settings').hide();	
		jQuery('#option_banner_header').hide();
		jQuery('#home_layout_setting').show();	
	});
	jQuery('#ui-id-9').click(function(){
		jQuery('#option_color_header1').hide();
		jQuery('#option_home').hide();
		jQuery('#option_general').hide();
		jQuery('#option_logo_header').hide();
		jQuery('#option_footer').hide();
		jQuery('#option_typography').hide();
		jQuery('#option_slug_settings').hide();	
		jQuery('#home_layout_setting').hide();	
		jQuery('#option_banner_header').show();	
	});
});
// js to active the link of option pannel
jQuery(document).ready(function() {
   jQuery('ul.options_tabs li ').click(function() {
		jQuery('ul.options_tabs li ').removeClass('active');
		jQuery(this).addClass('active');
   });
});